export class GovernanceError extends Error {
  readonly code: string;

  constructor(code: string, message: string) {
    super(message);
    this.name = "GovernanceError";
    this.code = code;
  }
}

export const GovernanceErrorCode = {
  MISSING_FIELD: "MISSING_FIELD",
  INVALID_VALUE: "INVALID_VALUE",
  AUTHORITY_MISSING: "AUTHORITY_MISSING",
  AUTHORITY_EXPIRED: "AUTHORITY_EXPIRED",
  AUTHORITY_REVOKED: "AUTHORITY_REVOKED",
  AUTHORITY_NOT_YET_VALID: "AUTHORITY_NOT_YET_VALID",
  AUTHORITY_SCOPE_MISMATCH: "AUTHORITY_SCOPE_MISMATCH",
  AUTHORITY_RESOURCE_MISMATCH: "AUTHORITY_RESOURCE_MISMATCH",
  AUTHORITY_CONDITION_FAILED: "AUTHORITY_CONDITION_FAILED",
  AUTHORITY_DELEGATION_INVALID: "AUTHORITY_DELEGATION_INVALID",
  POLICY_NOT_ACTIVE: "POLICY_NOT_ACTIVE",
  POLICY_IMMUTABLE: "POLICY_IMMUTABLE",
  GATE_FAILED: "GATE_FAILED",
  ROLLBACK_PLAN_REQUIRED: "ROLLBACK_PLAN_REQUIRED",
  ROLLBACK_PLAN_INVALID: "ROLLBACK_PLAN_INVALID",
  OVERRIDE_AUTHORITY_MISSING: "OVERRIDE_AUTHORITY_MISSING",
  LEDGER_MUTATION_FORBIDDEN: "LEDGER_MUTATION_FORBIDDEN",
  LEDGER_IDEMPOTENCY_CONFLICT: "LEDGER_IDEMPOTENCY_CONFLICT",
  ACTION_NOT_AUTHORIZED: "ACTION_NOT_AUTHORIZED",
  HUMAN_APPROVAL_REQUIRED: "HUMAN_APPROVAL_REQUIRED",
  TRACE_INCOMPLETE: "TRACE_INCOMPLETE",
} as const;

export type GovernanceErrorCode =
  (typeof GovernanceErrorCode)[keyof typeof GovernanceErrorCode];
