export class GovernanceError extends Error {
  readonly code: string;

  constructor(code: string, message: string) {
    super(message);
    this.name = "GovernanceError";
    this.code = code;
  }
}

export const GovernanceErrorCode = {
  MISSING_FIELD: "MISSING_FIELD",
  INVALID_VALUE: "INVALID_VALUE",
  AUTHORITY_MISSING: "AUTHORITY_MISSING",
  AUTHORITY_EXPIRED: "AUTHORITY_EXPIRED",
  AUTHORITY_REVOKED: "AUTHORITY_REVOKED",
  AUTHORITY_NOT_YET_VALID: "AUTHORITY_NOT_YET_VALID",
  AUTHORITY_SCOPE_MISMATCH: "AUTHORITY_SCOPE_MISMATCH",
  AUTHORITY_RESOURCE_MISMATCH: "AUTHORITY_RESOURCE_MISMATCH",
  AUTHORITY_CONDITION_FAILED: "AUTHORITY_CONDITION_FAILED",
  AUTHORITY_DELEGATION_INVALID: "AUTHORITY_DELEGATION_INVALID",
  POLICY_NOT_ACTIVE: "POLICY_NOT_ACTIVE",
  POLICY_IMMUTABLE: "POLICY_IMMUTABLE",
  GATE_FAILED: "GATE_FAILED",
  ROLLBACK_PLAN_REQUIRED: "ROLLBACK_PLAN_REQUIRED",
  ROLLBACK_PLAN_INVALID: "ROLLBACK_PLAN_INVALID",
  OVERRIDE_AUTHORITY_MISSING: "OVERRIDE_AUTHORITY_MISSING",
  LEDGER_MUTATION_FORBIDDEN: "LEDGER_MUTATION_FORBIDDEN",
  LEDGER_IDEMPOTENCY_CONFLICT: "LEDGER_IDEMPOTENCY_CONFLICT",
  ACTION_NOT_AUTHORIZED: "ACTION_NOT_AUTHORIZED",
  HUMAN_APPROVAL_REQUIRED: "HUMAN_APPROVAL_REQUIRED",
  TRACE_INCOMPLETE: "TRACE_INCOMPLETE",
  INVALID_STATE_TRANSITION: "INVALID_STATE_TRANSITION",
  EXECUTION_CLAIM_HELD: "EXECUTION_CLAIM_HELD",
  DUPLICATE_EXECUTION: "DUPLICATE_EXECUTION",
  RECOVERY_INVALID: "RECOVERY_INVALID",
  APPROVAL_DENIED: "APPROVAL_DENIED",
  APPROVAL_AUTHORITY_MISSING: "APPROVAL_AUTHORITY_MISSING",
  ROLLBACK_AUTHORITY_MISSING: "ROLLBACK_AUTHORITY_MISSING",
  CANARY_CONSTRAINT_FAILED: "CANARY_CONSTRAINT_FAILED",
  AUTHORIZATION_BINDING_MISMATCH: "AUTHORIZATION_BINDING_MISMATCH",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  RECONCILIATION_REQUIRED: "RECONCILIATION_REQUIRED",
  ROLLBACK_VERIFICATION_FAILED: "ROLLBACK_VERIFICATION_FAILED",
  EXECUTION_AUTHORITY_STALE: "EXECUTION_AUTHORITY_STALE",
  STORAGE_PERSISTENCE_FAILED: "STORAGE_PERSISTENCE_FAILED",
  STORAGE_INTEGRITY_FAILED: "STORAGE_INTEGRITY_FAILED",
  STORAGE_SCHEMA_UNSUPPORTED: "STORAGE_SCHEMA_UNSUPPORTED",
  STORAGE_TRANSACTION_FAILED: "STORAGE_TRANSACTION_FAILED",
} as const;

export type GovernanceErrorCode =
  (typeof GovernanceErrorCode)[keyof typeof GovernanceErrorCode];
