/**
 * Experimental CORE-03 / CORE-04 / Auditor extended surface.
 *
 * CORE-03 and CORE-04 are also re-exported from `@jiplabs/core` for 0.3.0
 * compatibility. Auditor stable symbols are on the root barrel from 1.1.0;
 * this subpath additionally exports experimental-only Auditor helpers.
 *
 * @experimental — CORE-03, CORE-04, and Auditor bridge/trace helpers only.
 */
export {
  EvaluationCorpus,
  InMemoryEvaluationCorpusStore,
  createEvaluationCaseCandidate,
  createEvaluationTarget,
  createCandidateFromGovernanceRun,
  isEvaluationWorthyOutcome,
  computeCandidateFingerprint,
  computeEvaluationRunFingerprint,
  buildEvaluationSummary,
  compareEvaluationToBaseline,
  createLearningSignal,
  createGovernanceRecommendation,
  type EvaluationCaseCandidate,
  type EvaluationCase,
  type EvaluationCaseVersion,
  type EvaluationSuiteVersion,
  type EvaluationTarget,
  type EvaluationRun,
  type EvaluationCaseResult,
  type EvaluationSummary,
  type EvaluationBaseline,
  type RegressionComparison,
  type RegressionAssessment,
  type LearningSignal,
  type GovernanceRecommendation,
  type EvaluationCorpusStore,
  type EvaluationCaseEvaluator,
  type EvaluationTargetRunner,
} from "./evaluation-corpus/index.js";

export {
  GovernedComponentRegistry,
  InMemoryGovernedComponentRegistryStore,
  createGovernedComponent,
  createAgentIdentity,
  createModelIdentity,
  createCapabilityDeclaration,
  createResponsibility,
  createQualificationRecord,
  createResponsibilityEligibility,
  createResponsibilityAssignment,
  createFallbackRelationship,
  createReplacementProposal,
  evaluateResponsibilityEligibility,
  validateValidatorIndependence,
  buildComponentGovernanceTraceRefs,
  selectEligibleComponent,
  isAssignmentEligible,
  type GovernedComponent,
  type AgentIdentity,
  type ModelIdentity,
  type CapabilityDeclaration,
  type Responsibility,
  type QualificationRequirement,
  type QualificationRecord,
  type ResponsibilityEligibility,
  type ResponsibilityAssignment,
  type GovernedComponentRegistryStore,
  type AssignmentPolicy,
  type ComponentSelectionPolicy,
  type ComponentGovernanceTraceRefs,
  type GovernedComponentType,
  type QualificationStatus,
  type EligibilityOutcome,
  type AssignmentMode,
  type ComponentRole,
  type ValidatorIndependencePolicy,
  type FallbackRelationship,
  type ReplacementProposal,
} from "./component-governance/index.js";

export {
  createAuditScope,
  createAuditTarget,
  createAuditEngagement,
  createAuditFinding,
  createAuditReport,
  computeAuditFindingFingerprint,
  createAuditFindingResolution,
  computeAuditStateFingerprint,
  buildAuditGovernedStateView,
  buildAuditGovernedStateViewFromTraceInput,
  computeGovernedStateContentHash,
  runAuditEngagement,
  assertAuditorIsObservationOnly,
  buildAuditSeveritySummary,
  buildAuditReportSummary,
  listUnresolvedFindingIds,
  compareFindingStatuses,
  getEffectiveFindingStatus,
  isFindingUnresolved,
  assertFindingHistoryPreserved,
  isEvaluationCandidateFromFinding,
  evaluationCaseSourceKindFromFinding,
  InMemoryAuditArtifactStore,
  type AuditAdvisory,
  type AuditEngagement,
  type AuditEngagementStatus,
  type AuditFinding,
  type AuditFindingClassification,
  type AuditFindingResolution,
  type AuditFindingSeverity,
  type AuditFindingStatus,
  type AuditGovernanceRef,
  type AuditGovernanceRefType,
  type AuditRemediation,
  type AuditReport,
  type AuditReportStatus,
  type AuditRuleEvaluator,
  type AuditRuleEvaluationInput,
  type AuditRuleEvaluationResult,
  type AuditRuleFindingDraft,
  type AuditScope,
  type AuditScopeKind,
  type AuditSeveritySummary,
  type AuditTarget,
  type AuditTimeRange,
  type AuditGovernedStateView,
  type AuditArtifactStore,
  type AuditorRunnerInput,
  type AuditorRunnerResult,
} from "./auditor/index.js";
