/**
 * Experimental CORE-03 / CORE-04 surface.
 *
 * These APIs are also re-exported from `@jiplabs/core` for 0.3.0 compatibility.
 * Importing from `@jiplabs/core/experimental` makes the stability boundary
 * explicit. SemVer for this subpath is not the 1.0 stable contract.
 *
 * @experimental
 */
export {
  EvaluationCorpus,
  InMemoryEvaluationCorpusStore,
  createEvaluationCaseCandidate,
  createEvaluationTarget,
  createCandidateFromGovernanceRun,
  isEvaluationWorthyOutcome,
  computeCandidateFingerprint,
  computeEvaluationRunFingerprint,
  buildEvaluationSummary,
  compareEvaluationToBaseline,
  createLearningSignal,
  createGovernanceRecommendation,
  type EvaluationCaseCandidate,
  type EvaluationCase,
  type EvaluationCaseVersion,
  type EvaluationSuiteVersion,
  type EvaluationTarget,
  type EvaluationRun,
  type EvaluationCaseResult,
  type EvaluationSummary,
  type EvaluationBaseline,
  type RegressionComparison,
  type RegressionAssessment,
  type LearningSignal,
  type GovernanceRecommendation,
  type EvaluationCorpusStore,
  type EvaluationCaseEvaluator,
  type EvaluationTargetRunner,
} from "./evaluation-corpus/index.js";

export {
  GovernedComponentRegistry,
  InMemoryGovernedComponentRegistryStore,
  createGovernedComponent,
  createAgentIdentity,
  createModelIdentity,
  createCapabilityDeclaration,
  createResponsibility,
  createQualificationRecord,
  createResponsibilityEligibility,
  createResponsibilityAssignment,
  createFallbackRelationship,
  createReplacementProposal,
  evaluateResponsibilityEligibility,
  validateValidatorIndependence,
  buildComponentGovernanceTraceRefs,
  selectEligibleComponent,
  isAssignmentEligible,
  type GovernedComponent,
  type AgentIdentity,
  type ModelIdentity,
  type CapabilityDeclaration,
  type Responsibility,
  type QualificationRequirement,
  type QualificationRecord,
  type ResponsibilityEligibility,
  type ResponsibilityAssignment,
  type GovernedComponentRegistryStore,
  type AssignmentPolicy,
  type ComponentSelectionPolicy,
  type ComponentGovernanceTraceRefs,
  type GovernedComponentType,
  type QualificationStatus,
  type EligibilityOutcome,
  type AssignmentMode,
  type ComponentRole,
  type ValidatorIndependencePolicy,
  type FallbackRelationship,
  type ReplacementProposal,
} from "./component-governance/index.js";
